"""empty message

Revision ID: 813edf2c0783
Revises: 
Create Date: 2023-10-16 15:23:35.399665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '813edf2c0783'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=8), nullable=False),
    sa.Column('resume', sa.String(length=128), nullable=True),
    sa.Column('role', sa.SmallInteger(), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('is_enable', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_is_enable'), ['is_enable'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_phone'), ['phone'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_phone'))
        batch_op.drop_index(batch_op.f('ix_user_is_enable'))

    op.drop_table('user')
    # ### end Alembic commands ###
