"""empty message

Revision ID: dd6cf4a6003a
Revises: 
Create Date: 2023-09-22 16:24:20.172374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd6cf4a6003a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=8), nullable=False),
    sa.Column('resume', sa.String(length=128), nullable=True),
    sa.Column('role', sa.SmallInteger(), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('is_enable', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_is_enable'), ['is_enable'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_phone'), ['phone'], unique=True)

    op.drop_table('administrator')
    with op.batch_alter_table('tb_score', schema=None) as batch_op:
        batch_op.drop_index('idx_stuNo_course')

    op.drop_table('tb_score')
    with op.batch_alter_table('flyway_schema_history', schema=None) as batch_op:
        batch_op.drop_index('flyway_schema_history_s_idx')

    op.drop_table('flyway_schema_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flyway_schema_history',
    sa.Column('installed_rank', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('script', mysql.VARCHAR(length=1000), nullable=False),
    sa.Column('checksum', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('installed_by', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('installed_on', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('execution_time', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('success', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('installed_rank'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('flyway_schema_history', schema=None) as batch_op:
        batch_op.create_index('flyway_schema_history_s_idx', ['success'], unique=False)

    op.create_table('tb_score',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stu_no', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('course', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('score', mysql.DECIMAL(precision=4, scale=1), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tb_score', schema=None) as batch_op:
        batch_op.create_index('idx_stuNo_course', ['stu_no', 'course'], unique=False)

    op.create_table('administrator',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('creator_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('role_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('name', mysql.VARCHAR(charset='utf8mb3', collation='utf8_general_ci', length=128), nullable=True, comment='管理员姓名'),
    sa.Column('password', mysql.VARCHAR(charset='utf8mb3', collation='utf8_general_ci', length=128), nullable=True, comment='密码'),
    sa.Column('avatar', mysql.VARCHAR(charset='utf8mb3', collation='utf8_general_ci', length=512), nullable=True, comment='语言'),
    sa.Column('type', mysql.CHAR(charset='utf8mb3', collation='utf8_general_ci', length=32), nullable=True, comment='管理员类型'),
    sa.Column('lang', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('info', mysql.JSON(), nullable=True, comment='信息：测试用json数据'),
    sa.Column('gmt_create', mysql.DATETIME(), nullable=True),
    sa.Column('gmt_modified', mysql.DATETIME(), nullable=True),
    sa.Column('v_action', mysql.VARCHAR(length=30), sa.Computed("(json_unquote(json_extract(`info`,_utf8mb4'$.action')))", persisted=False), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='框架测试表',
    mysql_comment='框架测试表',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_phone'))
        batch_op.drop_index(batch_op.f('ix_user_is_enable'))

    op.drop_table('user')
    # ### end Alembic commands ###
